CREATE DATABASE `rpps` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE `rpps` (
  `Type_d_identifiant_PP` varchar(255) DEFAULT NULL,
  `Identifiant_PP` varchar(255) DEFAULT NULL,
  `Identification_nationale_PP` varchar(255) DEFAULT NULL,
  `Code_civilite_exercice` varchar(255) DEFAULT NULL,
  `Libelle_civilite_exercice` varchar(255) DEFAULT NULL,
  `Nom_d_exercice` varchar(255) DEFAULT NULL,
  `Prenom_d_exercice` varchar(255) DEFAULT NULL,
  `Code_profession` varchar(255) DEFAULT NULL,
  `Libelle_profession` varchar(255) DEFAULT NULL,
  `Code_categorie_professionnelle` varchar(255) DEFAULT NULL,
  `Libelle_categorie_professionnelle` varchar(255) DEFAULT NULL,
  `Code_savoir_faire` varchar(255) DEFAULT NULL,
  `Libelle_savoir_faire` varchar(255) DEFAULT NULL,
  `Code_type_savoir_faire` varchar(255) DEFAULT NULL,
  `Libelle_type_savoir_faire` varchar(255) DEFAULT NULL,
  `Numero_SIRET_site` varchar(255) DEFAULT NULL,
  `Numero_SIREN_site` varchar(255) DEFAULT NULL,
  `Numero_FINESS_site` varchar(255) DEFAULT NULL,
  `Numero_FINESS_etablissement_juridique` varchar(255) DEFAULT NULL,
  `Raison_sociale_site` varchar(255) DEFAULT NULL,
  `Enseigne_commerciale_site` varchar(255) DEFAULT NULL,
  `Identifiant_structure` varchar(255) DEFAULT NULL,
  `Complement_destinataire` varchar(255) DEFAULT NULL,
  `Complement_point_geographique` varchar(255) DEFAULT NULL,
  `Numero_Voie` varchar(255) DEFAULT NULL,
  `Indice_repetition_voie` varchar(255) DEFAULT NULL,
  `Code_type_de_voie` varchar(255) DEFAULT NULL,
  `Libelle_type_de_voie` varchar(255) DEFAULT NULL,
  `Libelle_Voie` varchar(255) DEFAULT NULL,
  `Mention_distribution` varchar(255) DEFAULT NULL,
  `Bureau_cedex` varchar(255) DEFAULT NULL,
  `Code_postal` varchar(255) DEFAULT NULL,
  `Code_commune` varchar(255) DEFAULT NULL,
  `Libelle_commune` varchar(255) DEFAULT NULL,
  `Code_pays` varchar(255) DEFAULT NULL,
  `Libelle_pays` varchar(255) DEFAULT NULL,
  `Telephone` varchar(255) DEFAULT NULL,
  `Telephone_2` varchar(255) DEFAULT NULL,
  `Telecopie` varchar(255) DEFAULT NULL,
  `Adresse_e_mail` varchar(255) DEFAULT NULL,
  `Adresse_BAL_MSSante` varchar(255) DEFAULT NULL,
  KEY `rppsidx` (`Identifiant_PP`),
  KEY `nomidx` (`Nom_d_exercice`),
  KEY `profidx` (`Libelle_profession`),
  KEY `cpidx` (`Code_postal`),
  KEY `communeidx` (`Libelle_commune`),
  KEY `siteidx` (`Raison_sociale_site`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;